Know issue: When using gwibber, links that are opened in an external
browser may not open. Running gwibber from the command line will most
likely give you a similar error like the following.

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/gwibber/client.py", line 757, in <lambda>
    actHelpOnline.connect("activate", lambda *a: gintegration.load_url("https://answers.launchpad.net/gwibber"))
  File "/usr/lib/python2.6/site-packages/gwibber/gintegration.py", line 57, in load_url
    def load_url(url): gnome.url_show(url)
glib.GError: There was an error launching the default action command associated with this location.

This is most likely a link to a nonexistent firefox directory that hasn't
been updated by GConf upon firefox upgrades. You can verify this by running:

gconftool-2 -g /desktop/gnome/url-handlers/https/command

This command should return something like:

/usr/lib/firefox-3.5.2/firefox "%s"

You can use the symlink to firefox instead, as to avoid future issues
with firefox upgrades. To use the symlinks run the following commands.
Change commands for lib64 where appropriate.

gconftool-2 -s -t string /desktop/gnome/url-handlers/https/command '/usr/lib/firefox/firefox "%s"'
gconftool-2 -s -t string /desktop/gnome/url-handlers/http/command '/usr/lib/firefox/firefox "%s"'
gconftool-2 -s -t string /desktop/gnome/url-handlers/ftp/command '/usr/lib/firefox/firefox "%s"'
gconftool-2 -s -t string /desktop/gnome/url-handlers/chrome/command '/usr/lib/firefox/firefox "%s"'
